### ISSUE TITLE
[ui.env] as timeline

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#141]
[ui.env] has a great curve editor function, but is currently only for trigering signal envelope purposes. Would be nice to use the editor feature to also use it for controls, thus having a powerful timeline object.

Would it be possible to read the output of the raw curve value from a length or index value like tabread can do from a table?
Or have a separate  [ui.timeline], [ui.curve] or such object?

**Comment by 60-hz** [comment]
Ok: It is possible to use [env2array], then copy the envelope to [array define mytimeline] and finally use [array get mytimeline] to read the content. But I found it a bit convoluted and still think something like [getvalue $1( message and a second outlet to get the output would be a nice addition to [ui.env].

**Comment by uliss** [comment]
Yes, I agree. We can think about more convenient interface for such common case.
I see two possibilities:
- separate inlet that accept time in ms to get specified value
or
- message to object (for it seems that [at( would be more descriptive, because we are not getting samples by index as in array case, but getting value as specified time)

and second outlet for getting this values.

It should be added both to [ui.env] and [envelope]

**Comment by 60-hz** [comment]
While a separate input (second input) seems like a good solution, it would break a basic pd convention which is this: only the leftmost input triggers an output. Thus, using an [at (message in the first entry may be more "standard-compliant".
But I like both ideas ;)
