### ISSUE TITLE
CEAMMC for M1 Macs?

### ISSUE THREAD

**Issue by jaffasplaffa** [uliss/pure-data#177]
Hello :) 

I am trying to use to use the library on an M1 Macbook with PD.

When I open PD in Rosetta mode and open one of the helpfiles, I get the "developer cannot be verified" treatment and the externals doesn't work.

When I run Pd as a native M1 app, the externals also don't work.

So my question is, do you have any plans to update them, to run natively on M1 Macbook?

Thanks in advance,
Jaffa

**Comment by uliss** [comment]
Hello,

the upcoming release will support M1.
The release is planned to the end of November. If you need it earlier I can
send you current build

Best,
Serge

чт, 20 окт. 2022 г., 21:17 jaffasplaffa ***@***.***>:

**Comment by jaffasplaffa** [comment]
I would very much like a current build, if possible. Thank you!

**Comment by 60-hz** [comment]
If it is possible to have a link of current build also, I would be very happy to try it.

**Comment by uliss** [comment]
https://drive.google.com/file/d/10vjIp36DXK83zBxXeTY0K8Xvzt6RJfI0/view?usp=sharing

**Comment by 60-hz** [comment]
Thank you very much @uliss . Works well here on Monterey and M1 MacBook Pro.
Here are a few issues I found using it:

- pd-distribution: Using dark theme under macOS Monterey have a wrong default color layout in this pd distribution: black is replaces by white in some GUI, resulting in invisible cords / outlines / iemgui iolets / console text (Color theming was deactivated in vanilla on purpose).
<img width="275" alt="Capture d’écran 2022-10-21 à 14 56 54" src="https://user-images.githubusercontent.com/5449719/197201123-07ba3fa0-aaa9-4da9-99b7-33d480fc9719.png">

- [file]: object name clash with the new [file] object from pd vanilla since pd-0.52-2 (Could be rename file.io or whatever?)

- @value property is read only in [seq.counter]
```
[seq.counter] [@value] write check: readonly property
[seq.counter] can't set property: "@value"
```

- [seq.counter] @fold property is working only once. Forcing @inf doesn't seems to work.

- [system.cursor] red message sometimes when receive a "0" to turn it off): 
`#ceammc_cursor_class_receive: no such object`

- "+" or "-" message in right inlet of [flow.count] = crash (messages that trigger output could be sent in first inlet to follow pd "hot inlet" convention).

- Tried ceammc lib with the last pd-0.53 and it works well, though a red error is returned to the console after declaring the lib:
`[TCL] package error: can't find ctext package`

- [ui.faust~] / [lang.faust~] couldn't create, a red error is return:

`.../Pd/externals/ceammc/ui.faust~.pd_darwin: dlopen(.../Pd/externals/ceammc/ui.faust~.pd_darwin, 0x000A): symbol not found in flat namespace (_LLVMInitializeAArch64AsmParser)
/private/var/folders/fs/74nv__x57yd9k8q8h678r_fc0000gn/T/AppTranslocation/1CF6CEC8-9315-4C28-97F2-6C8F26B6123D/d/Pd-ceammc_2022.11-macosx-12.2.app/Contents/Resources/Scripts/../extra/ceammc/ui.faust~.pd_darwin: dlopen(/private/var/folders/fs/74nv__x57yd9k8q8h678r_fc0000gn/T/AppTranslocation/1CF6CEC8-9315-4C28-97F2-6C8F26B6123D/d/Pd-ceammc_2022.11-macosx-12.2.app/Contents/Resources/Scripts/../extra/ceammc/ui.faust~.pd_darwin, 0x000A): symbol not found in flat namespace (_LLVMInitializeAArch64AsmParser)
 ui.faust~ faust/ex0.dsp
... couldn't create`

**Comment by jaffasplaffa** [comment]
@uliss Thanks!

Is the only way to get it working, since it's not signed, to turn off gatekeeper?

**Comment by 60-hz** [comment]
@jaffasplaffa Here is an article that shows different way to open an unsigned app : https://www.macworld.com/article/672947/how-to-open-a-mac-app-from-an-unidentified-developer.html

**Comment by 60-hz** [comment]
You can also leave the gatekeeper active, and make an exception for only one app:
- open Terminal
- run `sudo xattr -rd com.apple.quarantine path/to/your/app`
- enter password, then only the app will run without gatekeeper's check.

**Comment by uliss** [comment]
Here's a new release, also for M1 (choose arm64)

https://github.com/uliss/pure-data/releases/tag/v2023.02

Closing.
