### ISSUE TITLE
[flow.append] don't accept some special characters

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#78]
[synth.eguitar~] help patch doesn't work since the object [flow.append @gate 0 @msg @delay 1000] returns :

`[flow.append] unknown property in argument list: @gate
`

it looks like @character is not supported by the object.

**Comment by uliss** [comment]
fixed in upcoming release:

if you need to use some special for ceammc library symbols in appended messages, like properties (starts with '@'),
you should quoted them in **flow.append** arguments

for example:
```
[123(
|
[flow.append "@message" 1 2 3  @delay 100]
|
[print]
```

will append [@message 1 2 3( after 100ms delay.

Non-special common messages can be non-quoted.
```
[flow.append reset @delay 1]
```
