### ISSUE TITLE
UI property panel don't display anymore

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#79]
Asking for any ui property windows doesn't display the panel anymore on recent pd version and ceammc-lib 0.9. No error message is displayed.

Pd-0.51-0 works
Pd-0.51-1 doesn't work -> bug: display tiny property screen which is buggy when resizing (see image)
Pd-0.51-2 doesn't work at all
Pd-0.51-3test1 doesn't work at all

Tested on OSX 10.15.4

![Capture d’écran 2020-10-18 à 13 35 38](https://user-images.githubusercontent.com/5449719/96366312-3c7b5d00-1147-11eb-8a0d-e44dbd5c1f41.png)

**Comment by 60-hz** [comment]
I made another test today (empty my external folders and deleted pd preferences files) and have a bit different behavior:

pd < 0.51-3 have some properties panel problems:

[ui.slider] doesn't work
[ui.knob] doesn't work
[ui.gain~] doesn't work
...
[ui.panelcolor] returns:

(Tcl) ERREUR : bad window path name ".gfxstub7f9828c388c0.t.cat_imgui"
    while executing
"ttk::label $id.t.cat_imgui.colorpanel -image [ceammc_category_icon var_catui.colorpanel_state]"
    (procedure "pdtk_ui.colorpanel_dialog" line 197)
    invoked from within
"pdtk_ui.colorpanel_dialog .gfxstub7f9828c388c0 {193 105} {(null)} {(null)} {0} {ui.colorpanel.0} {24 13} {0.93 0.93 0.93 1} {0.6 0.6 0.6 1} {0 0 0 1} ..."
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $docmds"

with pd-0.51-3 I have all properties panels bug like in the previous screenshot.

**Comment by uliss** [comment]
Thank you for verbose report. Seems to be fixed in upcoming release.

There are two reasons for this bugs:
- vanilla Pd switched to Tcl/Tk 8.6.10 (and it's great) but MacOSX build has broken **ttk** widget themes support. It does not support **aqua**. So temporary fix is use **alt** that is working. The right way is build vanilla Pd with manually builded Tcl/Tk/Wish. 
- **ui.colopanel** - fix our error

Could you check this build of external:
https://drive.google.com/file/d/1ibRlAk_5sSrX21Ed1Zz3542FTqWiyinY/view?usp=sharing

Hope, this could be fixed in upcoming release

**Comment by 60-hz** [comment]
I tried with the last Pd-0.51-4test2 and it looks to be fixed for most of ui objects.
Only ui.slider have a small window, but could be popped correctly when resizing.
![Capture d’écran 2020-12-17 à 22 19 10](https://user-images.githubusercontent.com/5449719/102546582-2989f800-40b8-11eb-8859-3c37b37baf5f.png)

![Capture d’écran 2020-12-17 à 22 19 31](https://user-images.githubusercontent.com/5449719/102546535-137c3780-40b8-11eb-938d-01b3baf352f4.png)
